# Generated by Django 4.1 on 2022-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='url',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
