# Generated by Django 4.1 on 2022-08-21 11:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bids_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), default=0, size=None),
            preserve_default=False,
        ),
    ]
