# Generated by Django 4.1 on 2022-08-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_bids_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bids_list',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='numBids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
