# Generated by Django 4.1 on 2022-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_user_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='numBids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
