# Generated by Django 4.1 on 2022-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionlisting_numbids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='numBids',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
