# Generated by Django 4.1 on 2022-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='uncategorized', max_length=60, null=True),
        ),
    ]
